app = "huvud"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  HEROKU_APP_NAME = "huvud-fly"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
