name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == github.event.repository.default_branch
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: fly releases
        env:
          FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"

      - run: fly releases --json
        env:
          FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"

      - run: |
          fly releases --json | jq 'max_by(.Version).Version'
        env:
          FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"

      - name: Create FLY_RELEASE_VERSION
        run: |
          echo "FLY_RELEASE_VERSION=$(fly releases --json | jq 'max_by(.Version).Version')" >> $GITHUB_ENV
        env:
          FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"

      - name: Print ENV
        run: |
          env | sort

      # - uses: dentarg/fly@main
      #   with:
      #     fly-token: ${{ secrets.FLY_API_TOKEN }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
